[2021-01-14 01:37:30,717: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:37:30,726: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:37:31,746: INFO/MainProcess] mingle: all alone
[2021-01-14 01:37:31,759: INFO/MainProcess] celery@25d298db418a ready.
[2021-01-14 01:38:03,982: INFO/MainProcess] Received task: create_task[c641905f-2e41-485f-bf3f-e1c395042ea5]  
[2021-01-14 01:38:14,009: INFO/ForkPoolWorker-7] Task create_task[c641905f-2e41-485f-bf3f-e1c395042ea5] succeeded in 10.021851999976207s: True
[2021-01-14 01:39:31,338: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:39:31,347: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:39:32,368: INFO/MainProcess] mingle: all alone
[2021-01-14 01:39:32,384: INFO/MainProcess] celery@54c6aa287b0e ready.
[2021-01-14 01:39:36,461: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-01-14 01:41:26,333: INFO/MainProcess] Received task: create_task[ea72d1fa-8074-4ee0-ad80-00759332b8a3]  
[2021-01-14 01:41:26,342: INFO/ForkPoolWorker-7] Task create_task[ea72d1fa-8074-4ee0-ad80-00759332b8a3] succeeded in 0.004026399983558804s: True
[2021-01-14 01:41:28,317: INFO/MainProcess] Received task: create_task[6969f29b-2782-43c2-8053-08ccf3c16c92]  
[2021-01-14 01:41:30,175: INFO/MainProcess] Received task: create_task[b8bca6eb-a207-40c0-bd54-a8f3dd4ec518]  
[2021-01-14 01:41:38,293: INFO/ForkPoolWorker-7] Task create_task[6969f29b-2782-43c2-8053-08ccf3c16c92] succeeded in 10.00758850001148s: True
[2021-01-14 01:41:40,194: INFO/ForkPoolWorker-8] Task create_task[b8bca6eb-a207-40c0-bd54-a8f3dd4ec518] succeeded in 10.014553199987859s: True
[2021-01-14 01:41:48,811: INFO/MainProcess] Received task: create_task[4b15e9a9-51a1-49e3-9ca4-4e0a8ae9e62c]  
[2021-01-14 01:41:58,785: INFO/ForkPoolWorker-7] Task create_task[4b15e9a9-51a1-49e3-9ca4-4e0a8ae9e62c] succeeded in 10.00516709999647s: True
[2021-01-14 01:42:52,854: INFO/MainProcess] Received task: create_task[ee9a5aa1-13ca-48d2-8d9c-536eb2c09219]  
[2021-01-14 01:42:54,284: INFO/MainProcess] Received task: create_task[9cc43def-fe23-4f2f-a705-5ad813f9eeb3]  
[2021-01-14 01:42:56,350: INFO/MainProcess] Received task: create_task[1146d22e-ea75-4f2c-869b-9b01ddbc468d]  
[2021-01-14 01:43:02,788: INFO/MainProcess] Received task: create_task[f8adced2-7969-47ae-bbfa-cc5da0139b5e]  
[2021-01-14 01:43:02,800: INFO/ForkPoolWorker-2] Task create_task[f8adced2-7969-47ae-bbfa-cc5da0139b5e] succeeded in 0.00705089999246411s: True
[2021-01-14 01:43:02,833: INFO/ForkPoolWorker-7] Task create_task[ee9a5aa1-13ca-48d2-8d9c-536eb2c09219] succeeded in 10.009377499984112s: True
[2021-01-14 01:43:03,686: INFO/MainProcess] Received task: create_task[2c4ce29a-d560-4144-a839-86b5f49ddd10]  
[2021-01-14 01:43:03,693: INFO/ForkPoolWorker-7] Task create_task[2c4ce29a-d560-4144-a839-86b5f49ddd10] succeeded in 0.001277000003028661s: True
[2021-01-14 01:43:04,266: INFO/ForkPoolWorker-8] Task create_task[9cc43def-fe23-4f2f-a705-5ad813f9eeb3] succeeded in 10.014550599997165s: True
[2021-01-14 01:43:04,314: INFO/MainProcess] Received task: create_task[f04f9887-8c54-4cc5-b976-86460fe0c8c5]  
[2021-01-14 01:43:04,318: INFO/ForkPoolWorker-7] Task create_task[f04f9887-8c54-4cc5-b976-86460fe0c8c5] succeeded in 0.001289300009375438s: True
[2021-01-14 01:43:26,333: INFO/ForkPoolWorker-1] Task create_task[1146d22e-ea75-4f2c-869b-9b01ddbc468d] succeeded in 30.012832799984608s: True
[2021-01-14 01:43:32,958: INFO/MainProcess] Received task: create_task[346c0193-cba3-44f5-b515-3160f10b1b24]  
[2021-01-14 01:44:02,937: INFO/ForkPoolWorker-7] Task create_task[346c0193-cba3-44f5-b515-3160f10b1b24] succeeded in 30.009259999991627s: True
[2021-01-14 01:44:29,190: INFO/MainProcess] Received task: create_task[29d57fce-3448-48a5-8990-9476f3f28b4b]  
[2021-01-14 01:44:59,184: INFO/ForkPoolWorker-7] Task create_task[29d57fce-3448-48a5-8990-9476f3f28b4b] succeeded in 30.02567619999172s: True
[2021-01-14 01:45:46,304: INFO/MainProcess] Received task: create_task[01688f09-4398-487c-b148-83c556336c4a]  
[2021-01-14 01:46:16,293: INFO/ForkPoolWorker-7] Task create_task[01688f09-4398-487c-b148-83c556336c4a] succeeded in 30.02043929998763s: True
[2021-01-14 01:46:19,768: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:46:19,776: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:46:20,798: INFO/MainProcess] mingle: all alone
[2021-01-14 01:46:20,814: INFO/MainProcess] celery@e40043a88881 ready.
[2021-01-14 01:46:25,087: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-01-14 01:46:36,647: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:46:36,658: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:46:37,301: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:46:37,312: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:46:37,375: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:46:37,385: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:46:37,680: INFO/MainProcess] mingle: all alone
[2021-01-14 01:46:37,694: INFO/MainProcess] celery@7050b2cf4c55 ready.
[2021-01-14 01:46:38,335: INFO/MainProcess] mingle: all alone
[2021-01-14 01:46:38,351: INFO/MainProcess] celery@659a4297895a ready.
[2021-01-14 01:46:38,406: INFO/MainProcess] mingle: all alone
[2021-01-14 01:46:38,421: INFO/MainProcess] celery@501350310ca8 ready.
[2021-01-14 01:46:42,651: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-01-14 01:46:42,651: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-01-14 01:46:42,651: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-01-14 01:46:59,789: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-01-14 01:46:59,803: INFO/MainProcess] mingle: searching for neighbors
[2021-01-14 01:47:00,828: INFO/MainProcess] mingle: all alone
[2021-01-14 01:47:00,845: INFO/MainProcess] celery@4573c70b4fee ready.
[2021-01-14 01:47:05,130: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-01-14 01:51:13,583: INFO/MainProcess] Received task: create_task[a0e758cb-ceac-4c66-9ee9-c2cf9cf74a71]  
[2021-01-14 01:51:13,589: INFO/ForkPoolWorker-7] Task create_task[a0e758cb-ceac-4c66-9ee9-c2cf9cf74a71] succeeded in 0.0032501999812666327s: True
[2021-12-11 04:18:25,325: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-11 04:18:25,333: INFO/MainProcess] mingle: searching for neighbors
[2021-12-11 04:18:26,350: INFO/MainProcess] mingle: all alone
[2021-12-11 04:18:26,358: INFO/MainProcess] celery@397dacb0af4c ready.
[2021-12-11 04:32:24,394: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-11 04:32:24,403: INFO/MainProcess] mingle: searching for neighbors
[2021-12-11 04:32:25,419: INFO/MainProcess] mingle: all alone
[2021-12-11 04:32:25,427: INFO/MainProcess] celery@0ac83b6628fa ready.
[2021-12-11 04:32:30,296: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-11 04:35:34,091: INFO/MainProcess] Received task: create_task[71aebe7d-4843-4f10-92e0-cf70df63824f]  
[2021-12-11 04:35:44,108: INFO/ForkPoolWorker-7] Task create_task[71aebe7d-4843-4f10-92e0-cf70df63824f] succeeded in 10.014155100012431s: True
[2021-12-11 04:39:57,989: INFO/MainProcess] Received task: create_task[f0a63824-7981-4185-b018-bb4154ea81db]  
[2021-12-11 04:40:06,458: INFO/MainProcess] Received task: create_task[807083e4-27a2-4be6-9d32-441e1b4b199c]  
[2021-12-11 04:40:16,477: INFO/ForkPoolWorker-8] Task create_task[807083e4-27a2-4be6-9d32-441e1b4b199c] succeeded in 10.016435600002296s: True
[2021-12-11 04:40:18,005: INFO/ForkPoolWorker-7] Task create_task[f0a63824-7981-4185-b018-bb4154ea81db] succeeded in 20.01335730002029s: True
[2021-12-11 04:51:19,876: INFO/MainProcess] Received task: create_task[ff66aa42-f960-47e3-8253-9ebd03fa7b1b]  
[2021-12-11 04:51:29,890: INFO/ForkPoolWorker-7] Task create_task[ff66aa42-f960-47e3-8253-9ebd03fa7b1b] succeeded in 10.00886729999911s: True
[2021-12-11 04:51:55,058: INFO/MainProcess] Received task: create_task[adbc93c6-902e-4baf-8ff1-61e18c5266a6]  
[2021-12-11 04:52:15,082: INFO/ForkPoolWorker-7] Task create_task[adbc93c6-902e-4baf-8ff1-61e18c5266a6] succeeded in 20.02129929998773s: True
[2021-12-11 04:52:26,124: INFO/MainProcess] Received task: create_task[1c258262-9a8d-47dc-9c72-ca82e6381639]  
[2021-12-11 04:52:36,135: INFO/ForkPoolWorker-7] Task create_task[1c258262-9a8d-47dc-9c72-ca82e6381639] succeeded in 10.00831560001825s: True
[2021-12-11 05:00:37,190: INFO/MainProcess] Received task: create_task[b6030ee3-1f93-4add-833a-bb9ac959d03a]  
[2021-12-11 05:00:39,254: INFO/MainProcess] Received task: create_task[d561016c-88f4-4ce0-aa32-2e5cde3839cb]  
[2021-12-11 05:00:49,265: INFO/ForkPoolWorker-8] Task create_task[d561016c-88f4-4ce0-aa32-2e5cde3839cb] succeeded in 10.004698900011135s: True
[2021-12-11 05:00:57,210: INFO/ForkPoolWorker-7] Task create_task[b6030ee3-1f93-4add-833a-bb9ac959d03a] succeeded in 20.01682429999346s: True
[2021-12-11 05:03:28,394: INFO/MainProcess] Received task: create_task[02b61d6b-3006-45d4-adae-f9a90c483999]  
[2021-12-11 05:03:38,400: INFO/ForkPoolWorker-7] Task create_task[02b61d6b-3006-45d4-adae-f9a90c483999] succeeded in 10.003930399980163s: True
[2021-12-11 05:04:01,525: INFO/MainProcess] Received task: create_task[4d1bed1b-5134-471d-9296-688350b794b2]  
[2021-12-11 05:04:11,532: INFO/ForkPoolWorker-7] Task create_task[4d1bed1b-5134-471d-9296-688350b794b2] succeeded in 10.004493199987337s: True
[2021-12-11 05:04:59,541: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-11 05:04:59,548: INFO/MainProcess] mingle: searching for neighbors
[2021-12-11 05:05:00,565: INFO/MainProcess] mingle: all alone
[2021-12-11 05:05:00,579: INFO/MainProcess] celery@7a2605926ae1 ready.
[2021-12-11 05:05:05,672: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-11 05:05:16,056: INFO/MainProcess] Received task: create_task[4cf796d6-d8f2-430d-96c5-25da8014de57]  
[2021-12-11 05:05:16,068: ERROR/ForkPoolWorker-7] Task create_task[4cf796d6-d8f2-430d-96c5-25da8014de57] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("C:/Work/myexpm/python-celery/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Work/myexpm/python-celery/myfile.txt'
[2021-12-11 05:06:07,836: INFO/MainProcess] Received task: create_task[cc8e046b-2147-42b9-8f2e-3501417bc8a2]  
[2021-12-11 05:06:07,841: ERROR/ForkPoolWorker-7] Task create_task[cc8e046b-2147-42b9-8f2e-3501417bc8a2] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("C:/Work/myexpm/python-celery/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Work/myexpm/python-celery/myfile.txt'
[2021-12-11 05:06:13,399: INFO/MainProcess] Received task: create_task[7ff44b0c-5a7d-4ddd-998b-80197397d028]  
[2021-12-11 05:06:13,405: ERROR/ForkPoolWorker-7] Task create_task[7ff44b0c-5a7d-4ddd-998b-80197397d028] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("C:/Work/myexpm/python-celery/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Work/myexpm/python-celery/myfile.txt'
[2021-12-11 05:06:33,951: INFO/MainProcess] Received task: create_task[472220ad-a530-427d-9759-02c1567186ba]  
[2021-12-11 05:06:33,956: ERROR/ForkPoolWorker-7] Task create_task[472220ad-a530-427d-9759-02c1567186ba] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("C:/Work/myexpm/python-celery/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Work/myexpm/python-celery/myfile.txt'
[2021-12-11 05:07:23,173: INFO/MainProcess] Received task: create_task[a3433820-383c-4bd3-ae16-08703b6180d3]  
[2021-12-11 05:07:23,195: ERROR/ForkPoolWorker-7] Task create_task[a3433820-383c-4bd3-ae16-08703b6180d3] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("C:/Work/myexpm/python-celery/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Work/myexpm/python-celery/myfile.txt'
[2021-12-11 05:08:53,240: INFO/MainProcess] Received task: create_task[d3052cb1-bc49-44db-bded-7423f033ee62]  
[2021-12-11 05:08:53,260: ERROR/ForkPoolWorker-7] Task create_task[d3052cb1-bc49-44db-bded-7423f033ee62] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("/logs/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Work/myexpm/python-celery/myfile.txt'
[2021-12-11 05:09:59,637: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-11 05:09:59,644: INFO/MainProcess] mingle: searching for neighbors
[2021-12-11 05:10:00,663: INFO/MainProcess] mingle: all alone
[2021-12-11 05:10:00,678: INFO/MainProcess] celery@cd6b7e81ef47 ready.
[2021-12-11 05:10:06,189: INFO/MainProcess] Received task: create_task[ba7a4046-f8ce-4716-82c9-014bfa7d8ecf]  
[2021-12-11 05:10:06,202: ERROR/ForkPoolWorker-7] Task create_task[ba7a4046-f8ce-4716-82c9-014bfa7d8ecf] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("/logs/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: '/logs/myfile.txt'
[2021-12-11 05:10:06,568: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-11 05:11:37,532: INFO/MainProcess] Received task: create_task[7d58e1bd-2665-4176-b391-91fa0935052f]  
[2021-12-11 05:11:37,541: ERROR/ForkPoolWorker-7] Task create_task[7d58e1bd-2665-4176-b391-91fa0935052f] raised unexpected: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 36, in create_task
    with open("/usr/src/app/myfile.txt", "w") as file1:
FileNotFoundError: [Errno 2] No such file or directory: '/logs/myfile.txt'
[2021-12-11 05:12:12,313: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-11 05:12:12,320: INFO/MainProcess] mingle: searching for neighbors
[2021-12-11 05:12:13,343: INFO/MainProcess] mingle: all alone
[2021-12-11 05:12:13,367: INFO/MainProcess] celery@1adbe2d80cba ready.
[2021-12-11 05:12:18,703: INFO/MainProcess] Received task: create_task[e8727e58-b770-45b3-be68-e9d816293f29]  
[2021-12-11 05:12:18,721: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:12:18,727: INFO/ForkPoolWorker-7] Task create_task[e8727e58-b770-45b3-be68-e9d816293f29] succeeded in 0.020959300018148497s: True
[2021-12-11 05:12:18,950: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-11 05:12:48,134: INFO/MainProcess] Received task: create_task[269bebc7-dfc1-46e0-a949-ccf7f0a32124]  
[2021-12-11 05:12:48,143: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:12:48,163: INFO/ForkPoolWorker-7] Task create_task[269bebc7-dfc1-46e0-a949-ccf7f0a32124] succeeded in 0.023899299994809553s: True
[2021-12-11 05:13:02,170: INFO/MainProcess] Received task: create_task[bf92051b-2003-4395-b9b7-9767ac6c9f59]  
[2021-12-11 05:13:02,175: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:13:02,177: INFO/ForkPoolWorker-7] Task create_task[bf92051b-2003-4395-b9b7-9767ac6c9f59] succeeded in 0.004597000021021813s: True
[2021-12-11 05:14:32,473: INFO/MainProcess] Received task: create_task[99cde5e4-d234-4898-a49b-5c0177a9b781]  
[2021-12-11 05:14:32,479: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:14:32,488: INFO/ForkPoolWorker-7] Task create_task[99cde5e4-d234-4898-a49b-5c0177a9b781] succeeded in 0.011570000002393499s: True
[2021-12-11 05:14:37,053: INFO/MainProcess] Received task: create_task[04aee236-0afb-422e-bf52-9ee4713af147]  
[2021-12-11 05:14:37,060: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:14:37,063: INFO/ForkPoolWorker-7] Task create_task[04aee236-0afb-422e-bf52-9ee4713af147] succeeded in 0.005871100001968443s: True
[2021-12-11 05:14:54,523: INFO/MainProcess] Received task: create_task[0b2b92dd-c072-4322-b4fd-5a17f07e29a5]  
[2021-12-11 05:14:54,532: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:14:54,536: INFO/ForkPoolWorker-7] Task create_task[0b2b92dd-c072-4322-b4fd-5a17f07e29a5] succeeded in 0.007533600000897422s: True
[2021-12-11 05:15:24,129: INFO/MainProcess] Received task: create_task[6364ef58-b857-4368-9735-bb01108bb45d]  
[2021-12-11 05:15:24,135: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:15:24,137: INFO/ForkPoolWorker-7] Task create_task[6364ef58-b857-4368-9735-bb01108bb45d] succeeded in 0.004657100012991577s: True
[2021-12-11 05:15:39,036: INFO/MainProcess] Received task: create_task[88936685-7a31-4ce0-badc-1e5130de5aac]  
[2021-12-11 05:15:39,053: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:15:39,058: INFO/ForkPoolWorker-7] Task create_task[88936685-7a31-4ce0-badc-1e5130de5aac] succeeded in 0.018686299998080358s: True
[2021-12-11 05:15:46,666: INFO/MainProcess] Received task: create_task[8795dfdd-6b48-4d8b-9336-e7ff0aab233c]  
[2021-12-11 05:15:46,672: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:15:46,673: INFO/ForkPoolWorker-7] Task create_task[8795dfdd-6b48-4d8b-9336-e7ff0aab233c] succeeded in 0.00431150000076741s: True
[2021-12-11 05:15:46,856: INFO/MainProcess] Received task: create_task[81a9454b-3af9-4275-b8fd-d0d9984ed81f]  
[2021-12-11 05:15:46,863: WARNING/ForkPoolWorker-7] {
        "eBooks":[
            {
                "language":"Pascal",
                "edition":"third"
            },
            {
                "language":"Python",
                "edition":"four"
            },
            {
                "language":"SQL",
                "edition":"second"
            }
        ]
    }
[2021-12-11 05:15:46,865: INFO/ForkPoolWorker-7] Task create_task[81a9454b-3af9-4275-b8fd-d0d9984ed81f] succeeded in 0.00524200001382269s: True
